version: '3'
services:
    api:
        build: ./
        image: apiwilder
        container_name: api
        ports: 
            - 5000:5000
        volumes: 
            - ./src:/app/src/
    db:
        image: postgres
        container_name: db
        environment:
          POSTGRES_PASSWORD: superKeyDev
        ports: 
            - 5432:5432